//! 监控页「自定义 JS 表达式」筛选的求值器。
//!
//! 与 `routing::model_script` 是**两套东西**，别混：那个改模型名、住在网关
//! 请求热路径上；这个只回答「这一条日志要不要显示」，住在监控页的查询命令里。
//! 共用的是同一套引擎约束（rquickjs、线程本地、超时 + 内存上限、异常必须取走）。
//!
//! 表达式为什么在后端而不是前端求值：日志是**分页**的，而请求/响应原文存在
//! 另一张 `captures` 表里。前端只拿得到当前这一页，拿不到全量的报文 ——
//! 于是「筛出所有请求体里带 tools 的请求」在前端根本无从做起。所以匹配必须
//! 发生在分页**之前**，只能在能同时看到 logs 与 captures 的地方做。
//!
//! 前端仍保留一份同语义的求值（`src/lib/logExpr.ts`），但只用于「进行中」的
//! 请求 —— 那些还没落库、没有 captures，也就没有分页问题。

use std::cell::{Cell, RefCell};
use std::time::{Duration, Instant};

use rquickjs::{Context, Function, Runtime};

/// 单行的求值上限。用户脚本只该做几个字符串比较，撞上它多半是写坏了。
const ROW_TIMEOUT: Duration = Duration::from_millis(50);

/// 整批求值的总预算。
///
/// 单行超时挡不住「一行很快、但有一万行」的组合 —— 那会把 tokio 的工作线程
/// 占住几十秒，监控页整个卡死。总预算给整批一个硬上限，超了就整批报错。
const TOTAL_BUDGET: Duration = Duration::from_millis(500);

/// 脚本可用的堆上限，挡 `"x".repeat(1e9)` 这类写法。
const MEMORY_LIMIT: usize = 8 * 1024 * 1024;

thread_local! {
    /// 每线程一份引擎，惰性创建。不用 `static Mutex<Engine>`：`Runtime`/`Context`
    /// 不是 `Send`/`Sync`（同 `model_script` 的理由），塞进 static 编译不过。
    static ENGINE: RefCell<Option<Engine>> = const { RefCell::new(None) };
}

struct Engine {
    ctx: Context,
    /// interrupt handler 读的截止时刻。注册一次、每次求值前改写，比反复挂 handler 便宜。
    deadline: std::rc::Rc<Cell<Option<Instant>>>,
}

/// 把用户表达式包成 `(__json) => boolean`。返回的两种写法都试，谁先编译用谁。
///
/// 试两种是因为用户自然会先写 `ctx.status === 500`（表达式），认真起来又会写
/// `if (ctx.latencyMs > 1000) return true`（语句体）。只支持一种，另一种就会
/// 报一个和真实意图毫无关系的语法错。
///
/// 把 ctx 当 JSON 字符串传进来再 `JSON.parse`，而不是逐个字段往 JS 上挂：
/// 内置对象是嵌套的（request/response/upstreamRequest/upstreamResponse），
/// 手写转换要写一堆递归，而 `JSON.parse` 一行就是全部。开销在几十微秒量级，
/// 相对筛选的场景可以忽略。
fn candidates(source: &str) -> [String; 2] {
    [
        // 表达式形式：`ctx.model.includes("sonnet")`
        format!("((__json) => {{ const ctx = JSON.parse(__json); return !!({source}); }})"),
        // 语句体形式：`if (ctx.status >= 400) return true; return false;`
        //
        // 先包一层 IIFE 再取真假值：用户 `return` 出来的可能是字符串或数字，
        // 而 Rust 侧按 `bool` 取结果 —— 不在这里归一，`ctx.model` 这种完全
        // 自然的写法会撞上「string 转不成 bool」。
        format!(
            "((__json) => {{ const ctx = JSON.parse(__json); const __r = (() => {{ {source} }})(); return !!__r; }})"
        ),
    ]
}

/// 从挂起的异常里挖出用户看得懂的错因，**并把它取走**。
///
/// QuickJS 的 `Error::to_string()` 只给「Exception generated by QuickJS」这种
/// 壳，真正有用的 message 挂在异常对象上。用户写 `throw new Error("boom")` 时
/// 要看的是 boom；语法错也一样，`unexpected token` 远比那句壳有用。
///
/// 取走挂起异常是必须的：不清掉的话，下一次求值会立刻在同一份异常上翻车。
fn exception_message(ctx: &rquickjs::Ctx<'_>, err: &rquickjs::Error) -> String {
    let caught = ctx.catch();
    if let Some(obj) = caught.as_object() {
        if let Ok(m) = obj.get::<_, String>("message") {
            return m;
        }
    }
    // `throw "boom"` 抛的是裸字符串，没有 message 可取。
    if let Some(s) = caught.as_string().and_then(|s| s.to_string().ok()) {
        return s;
    }
    err.to_string()
}

impl Engine {
    fn new() -> rquickjs::Result<Self> {
        let rt = Runtime::new()?;
        rt.set_memory_limit(MEMORY_LIMIT);

        let deadline: std::rc::Rc<Cell<Option<Instant>>> = std::rc::Rc::new(Cell::new(None));
        let watch = deadline.clone();
        rt.set_interrupt_handler(Some(Box::new(move || {
            watch.get().is_some_and(|at| Instant::now() >= at)
        })));

        let ctx = Context::full(&rt)?;
        Ok(Self { ctx, deadline })
    }

    /// 编译并逐行求值，全程留在同一个 `ctx.with` 里。
    ///
    /// 不能把编译好的 `Function` 带出闭包：它的生命周期绑在 `Ctx` 上，跨出去
    /// 编译不过。`model_script` 也是把整段求值放在闭包里，这里照做。
    fn run_all(
        &self,
        source: &str,
        contexts: &[serde_json::Value],
    ) -> Result<Vec<bool>, String> {
        self.ctx.with(|ctx| {
            let f = Self::compile(&ctx, source)?;

            let started = Instant::now();
            let mut out = Vec::with_capacity(contexts.len());
            for c in contexts {
                if started.elapsed() > TOTAL_BUDGET {
                    return Err(
                        "表达式执行超时：请检查脚本里是否有死循环或过大的循环".into(),
                    );
                }
                self.deadline.set(Some(Instant::now() + ROW_TIMEOUT));
                let r: rquickjs::Result<bool> = f.call((c.to_string(),));
                self.deadline.set(None);
                match r {
                    Ok(b) => out.push(b),
                    Err(e) => {
                        return Err(exception_message(&ctx, &e));
                    }
                }
            }
            Ok(out)
        })
    }

    /// 只编译、不求值。给编辑框做行内报错用。
    fn compile_only(&self, source: &str) -> Result<(), String> {
        self.ctx.with(|ctx| Self::compile(&ctx, source).map(|_| ()))
    }

    /// 编译用户表达式。两种包装都试，谁先成功用谁。
    ///
    /// 返回的 `Function` 绑在 JS 上下文的 `'js` 上，**不是** `ctx` 那个借用 ——
    /// 写成 `Function<'_>` 编译器会要求两个生命周期同一个，那就没法只在
    /// `with` 闭包里借一下 `ctx` 了。
    fn compile<'js>(ctx: &rquickjs::Ctx<'js>, source: &str) -> Result<Function<'js>, String> {
        let mut last_err = String::new();
        for cand in candidates(source) {
            match ctx.eval::<Function, _>(cand) {
                Ok(f) => return Ok(f),
                Err(e) => {
                    last_err = exception_message(&ctx, &e);
                }
            }
        }
        Err(last_err)
    }
}

/// 检查表达式能否编译，`Err` 是给编辑框做行内报错用的错因。
pub fn validate(source: &str) -> Result<(), String> {
    if source.trim().is_empty() {
        return Ok(());
    }
    with_engine(|e| e.compile_only(source), || Ok(()))
}

/// 对一批 ctx 求值，返回每行是否命中。
///
/// `Err` 有两种：表达式编译不过（语法错），或整批超出总预算。前者是用户要改的
/// 问题，后者通常是脚本写成了死循环 —— 两种都该原样告诉用户，而不是静默返回
/// 空结果（那看起来就像「没有匹配的请求」，会把用户引到完全错误的方向）。
pub fn filter(source: &str, contexts: &[serde_json::Value]) -> Result<Vec<bool>, String> {
    if source.trim().is_empty() {
        return Ok(vec![true; contexts.len()]);
    }

    with_engine(|engine| engine.run_all(source, contexts), || Ok(vec![true; contexts.len()]))
}

/// 和 `model_script` 同款的线程本地引擎取用。
///
/// 引擎起不来（QuickJS 分配失败）时**不报错**：筛选条件失效等于「不筛」，
/// 比整页查询失败温和得多。日志里留一条 warn 就够了。
fn with_engine<T>(
    f: impl FnOnce(&Engine) -> Result<T, String>,
    on_init_failure: impl FnOnce() -> Result<T, String>,
) -> Result<T, String> {
    ENGINE.with(|slot| {
        let mut slot = slot.borrow_mut();
        if slot.is_none() {
            match Engine::new() {
                Ok(engine) => *slot = Some(engine),
                Err(e) => {
                    tracing::warn!(error = %e, "筛选表达式引擎初始化失败，自定义筛选不生效");
                    return on_init_failure();
                }
            }
        }
        f(slot.as_ref().expect("上面刚填过"))
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn ctx() -> serde_json::Value {
        json!({
            "model": "claude-opus-5-5",
            "requestModel": "claude-fable-5-1",
            "status": 200,
            "latencyMs": 1200,
            "request": { "method": "POST", "body": { "temperature": 0 } },
            "upstreamResponse": { "status": 200, "body": { "id": "x" } },
        })
    }

    #[test]
    fn empty_source_matches_everything() {
        assert_eq!(filter("", &[ctx(), ctx()]).unwrap(), vec![true, true]);
    }

    #[test]
    fn expression_form_is_supported() {
        let out = filter(r#"ctx.status === 200"#, &[ctx()]).unwrap();
        assert_eq!(out, vec![true]);
    }

    #[test]
    fn statement_form_is_supported() {
        let out = filter("if (ctx.latencyMs > 1000) { return true; }\nreturn false;", &[ctx()]).unwrap();
        assert_eq!(out, vec![true]);
    }

    #[test]
    fn nested_bodies_are_reachable() {
        // 内置对象的嵌套结构必须真的能读到底 —— 这是「按响应体筛」的全部意义。
        let out = filter(r#"ctx.upstreamResponse.body.id === "x""#, &[ctx()]).unwrap();
        assert_eq!(out, vec![true]);
    }

    #[test]
    fn a_missing_field_is_falsy_not_a_crash() {
        // 进行中的请求没有 upstreamResponse。读它的属性该得到 undefined（假值），
        // 而不是抛异常让整批查询失败。
        let partial = json!({ "status": 200 });
        let out = filter(r#"ctx.upstreamResponse?.body?.id === "x""#, &[partial]).unwrap();
        assert_eq!(out, vec![false]);
    }

    #[test]
    fn syntax_error_is_reported() {
        let err = filter("ctx.status === ", &[ctx()]).unwrap_err();
        assert!(!err.is_empty(), "语法错必须带出原因给用户看");
    }

    #[test]
    fn throw_is_reported_not_swallowed() {
        // 脚本自己 throw 时不能静默变成「没匹配」，那会误导用户去改筛选条件。
        let err = filter(r#"throw new Error("boom")"#, &[ctx()]).unwrap_err();
        assert!(err.contains("boom"), "应带上原始错误：{err}");
    }

    #[test]
    fn non_boolean_return_is_coerced_to_truthiness() {
        // `ctx.model` 这种返回字符串的写法很自然，该按真假值处理。
        assert_eq!(filter("ctx.model", &[ctx()]).unwrap(), vec![true]);
        assert_eq!(filter("''", &[ctx()]).unwrap(), vec![false]);
    }

    #[test]
    fn validate_accepts_both_forms_and_empty() {
        assert!(validate("").is_ok());
        assert!(validate("ctx.status === 200").is_ok());
        assert!(validate("return ctx.status === 200").is_ok());
    }

    #[test]
    fn validate_reports_syntax_error() {
        assert!(validate("ctx.status === ").is_err());
    }

    #[test]
    fn a_scope_leak_between_rows_does_not_happen() {
        // 用户写 `const x = 1` 时，第二行不该撞上「重复声明」——
        // 每行都在同一个箭头函数的调用里，作用域是干净的。
        let out = filter("const x = ctx.status; return x === 200;", &[ctx(), ctx()]).unwrap();
        assert_eq!(out, vec![true, true]);
    }
}